# Generated by Django 6.0.7 on 2026-07-20 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotConversationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_user_id', models.CharField(max_length=64, unique=True)),
                ('state', models.CharField(choices=[('waiting_full_name', 'Ожидание ФИО'), ('waiting_sbp_phone', 'Ожидание телефона СБП'), ('waiting_experience', 'Ожидание опыта'), ('waiting_portfolio', 'Ожидание портфолио')], max_length=64)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('sbp_phone', models.CharField(blank=True, max_length=32)),
                ('experience_text', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_user_id', models.CharField(max_length=64, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('sbp_phone', models.CharField(max_length=32)),
                ('experience_text', models.TextField()),
                ('portfolio_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('callback_base_url', models.URLField(blank=True)),
                ('site_token', models.CharField(max_length=255)),
                ('site_secret', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HubBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=64, unique=True)),
                ('local_brief_id', models.PositiveIntegerField()),
                ('brief_number', models.CharField(max_length=64)),
                ('client_ref', models.CharField(max_length=128)),
                ('model_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('agreed_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('designer_share_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('site_share_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('has_stl', models.BooleanField(default=False)),
                ('screenshots_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('queued', 'В очереди'), ('assigned', 'Назначена'), ('in_progress', 'В работе'), ('needs_clarification', 'Нужно уточнение'), ('clarification_provided', 'Уточнение получено'), ('done', 'Готово'), ('cancelled', 'Отменено')], default='queued', max_length=32)),
                ('eta', models.CharField(blank=True, max_length=128)),
                ('last_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('designer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_briefs', to='hub.designer')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='briefs', to='hub.sitenode')),
            ],
        ),
        migrations.CreateModel(
            name='HubBriefEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64, unique=True)),
                ('event', models.CharField(max_length=64)),
                ('payload_json', models.JSONField(default=dict)),
                ('delivered_ok', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='hub.hubbrief')),
            ],
        ),
        migrations.AddConstraint(
            model_name='hubbrief',
            constraint=models.UniqueConstraint(fields=('site', 'local_brief_id'), name='uniq_brief_per_site_local_id'),
        ),
    ]
