# Generated by Django 6.0.7 on 2026-07-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_designer_web_login_designer_web_password_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubbrief',
            name='designer_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hubbrief',
            name='final_model_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='hubbrief',
            name='final_screenshots_urls',
            field=models.TextField(blank=True),
        ),
    ]
