# Generated by Django 6.0.7 on 2026-07-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_hubbrief_designer_comment_hubbrief_final_model_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubbrief',
            name='source_stl_file',
            field=models.FileField(blank=True, upload_to='hub/source-stl/'),
        ),
        migrations.AddField(
            model_name='hubbrief',
            name='stl_sync_error',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
