# Generated by Django 6.0.7 on 2026-07-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_hubbrief_source_stl_file_hubbrief_stl_sync_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubbrief',
            name='final_model_file',
            field=models.FileField(blank=True, upload_to='hub/final-models/'),
        ),
        migrations.AddField(
            model_name='hubbrief',
            name='final_screenshots_archive',
            field=models.FileField(blank=True, upload_to='hub/final-screenshots/'),
        ),
    ]
