# Generated by Django 6.0.7 on 2026-07-21 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_hubbrief_final_model_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubAdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('web_login', models.CharField(max_length=64, unique=True)),
                ('web_password_hash', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('can_manage_users', models.BooleanField(default=True)),
                ('can_manage_briefs', models.BooleanField(default=True)),
                ('can_view_ratings', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='designer',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='designer',
            name='ratings_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DesignerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64, unique=True)),
                ('score', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('rated_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='hub.hubbrief')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='hub.designer')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='hub.sitenode')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('score__gte', 1), ('score__lte', 5)), name='rating_score_1_5')],
            },
        ),
    ]
